# Generated by Django 5.2.3 on 2025-07-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_first_time_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='one_time_use',
            field=models.BooleanField(default=False),
        ),
    ]
