# Generated by Django 4.2.5 on 2025-08-06 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_coupon_one_time_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coupon_images/'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='terms_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AutoRewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_total_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_order_count', models.PositiveIntegerField(blank=True, null=True)),
                ('min_items_per_order', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon')),
            ],
        ),
    ]
