# Generated by Django 4.2.5 on 2025-08-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_base_price_product_shipping_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price_we_buy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
