# Generated by Django 5.2.3 on 2025-08-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productvariant_price_we_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
