# Generated by Django 5.2.3 on 2025-09-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_height_cm_product_length_cm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width_cm',
        ),
    ]
