# Generated by Django 5.2.3 on 2025-09-07 15:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_height_cm_remove_product_length_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.0'), help_text='Height of product in cm', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.0'), help_text='Length of product in cm', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), help_text='Weight of product in kg', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.0'), help_text='Width of product in cm', max_digits=6),
        ),
    ]
