# Generated by Django 4.2.5 on 2025-08-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='aadhar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_docs/aadhar/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='pan_photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_docs/pan/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='sellerdraft',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='sellerdraft',
            name='aadhar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_docs/aadhar/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='sellerdraft',
            name='pan_photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_docs/pan/%Y/%m/'),
        ),
    ]
