# Generated by Django 4.2.5 on 2025-08-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_aadhar_number_seller_aadhar_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerdraft',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
