# Generated by Django 5.2.3 on 2025-08-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_otp_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='otp_created_at',
        ),
    ]
