# Generated by Django 5.2.3 on 2025-07-31 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_review', '0002_alter_review_rating_reviewmedia_delete_reviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review_images/')),
                ('image1', models.ImageField(upload_to='review_images/')),
                ('image2', models.ImageField(upload_to='review_images/')),
                ('image3', models.ImageField(upload_to='review_images/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_review.review')),
            ],
        ),
        migrations.DeleteModel(
            name='ReviewMedia',
        ),
    ]
