# Generated by Django 4.2.5 on 2025-08-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_review', '0003_alter_review_rating_reviewimage_delete_reviewmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimage',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='image3',
        ),
    ]
