# Generated by Django 4.2.5 on 2025-08-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_review', '0004_remove_reviewimage_image1_remove_reviewimage_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
