# Generated by Django 4.2.5 on 2025-08-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_review', '0005_reviewimage_image1_reviewimage_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimage',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='image3',
        ),
    ]
