# Generated by Django 4.2.5 on 2025-08-26 17:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_product_seller'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(blank=True, max_length=7)),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='drafts/color/%Y/%m/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='drafts/color/%Y/%m/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='drafts/color/%Y/%m/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='drafts/color/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='SellerProductMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment'), ('both', 'Both Available')], default='both', max_length=10)),
                ('shipping_by', models.CharField(choices=[('seller', 'Shipping by Seller'), ('yourbaazar', 'Shipping by YourBaazar')], default='yourbaazar', max_length=15)),
                ('minimum_shipping', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('length_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('width_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('height_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('size_price_explanation', models.TextField(blank=True)),
                ('is_extended_color_of_existing', models.BooleanField(default=False)),
                ('existing_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_meta', to='product.product')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='product.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_meta', to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerProductDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_other', models.CharField(blank=True, max_length=120)),
                ('subcategory_other', models.CharField(blank=True, max_length=120)),
                ('product_type_other', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100)),
                ('short_description', models.TextField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='drafts/thumbnails/%Y/%m/')),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_shipping', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment'), ('both', 'Both Available')], default='both', max_length=10)),
                ('shipping_by', models.CharField(choices=[('seller', 'Shipping by Seller'), ('yourbaazar', 'Shipping by YourBaazar')], default='yourbaazar', max_length=15)),
                ('length_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('width_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('height_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_extended_color_of_existing', models.BooleanField(default=False)),
                ('size_price_explanation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_drafts', to='product.product')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
                ('existing_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_color_drafts', to='product.product')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product_type')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_drafts', to='seller.seller')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='DraftVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price_before_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('price_we_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='seller_products.draftcolor')),
            ],
        ),
        migrations.AddField(
            model_name='draftcolor',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='seller_products.sellerproductdraft'),
        ),
        migrations.AddIndex(
            model_name='sellerproductdraft',
            index=models.Index(fields=['seller', 'status'], name='seller_prod_seller__637917_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerproductdraft',
            index=models.Index(fields=['sku'], name='seller_prod_sku_8fb8a9_idx'),
        ),
    ]
