# Generated by Django 5.2.3 on 2025-09-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerproductdraft',
            name='existing_product',
        ),
        migrations.RemoveField(
            model_name='sellerproductdraft',
            name='is_extended_color_of_existing',
        ),
        migrations.RemoveField(
            model_name='sellerproductmeta',
            name='existing_product',
        ),
        migrations.RemoveField(
            model_name='sellerproductmeta',
            name='is_extended_color_of_existing',
        ),
        migrations.AlterField(
            model_name='sellerproductdraft',
            name='shipping_by',
            field=models.CharField(choices=[('yourbaazar', 'Shipping by YourBaazar')], default='yourbaazar', max_length=15),
        ),
        migrations.AlterField(
            model_name='sellerproductmeta',
            name='shipping_by',
            field=models.CharField(choices=[('yourbaazar', 'Shipping by YourBaazar')], default='yourbaazar', max_length=15),
        ),
    ]
