# Generated by Django 4.2.5 on 2025-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0004_contact_us_created_at_contact_us_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
