# Generated by Django 4.2.5 on 2025-08-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0005_contact_us_is_resolved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nav_image',
            new_name='NavImage',
        ),
    ]
