# Generated by Django 4.2.5 on 2025-08-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0006_rename_nav_image_navimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='navimage',
            name='carasoul_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='navimage',
            name='carasoul_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
