# Generated by Django 4.2.5 on 2025-08-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0007_navimage_carasoul_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('womens_image', models.ImageField(blank=True, null=True, upload_to='collection_images/')),
                ('mens_image', models.ImageField(blank=True, null=True, upload_to='collection_images/')),
                ('accessories_image', models.ImageField(blank=True, null=True, upload_to='collection_images/')),
                ('womens_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('mens_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('accessories_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('womens_paragraph', models.TextField(blank=True, null=True)),
                ('mens_paragraph', models.TextField(blank=True, null=True)),
                ('accessories_paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shop_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_image', models.ImageField(blank=True, null=True, upload_to='sale_images/')),
                ('sale_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_discount', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
