# Generated by Django 5.2.3 on 2025-10-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0008_collection_card_shop_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('desktop_image', models.ImageField(blank=True, null=True, upload_to='festival_slides/desktop/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='festival_slides/mobile/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
