# Generated by Django 4.2.5 on 2025-08-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallettransaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
