# Generated by Django 4.2.5 on 2025-08-26 17:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('business_name', models.CharField(blank=True, max_length=160)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='seller_reviews/%Y/%m/')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('experience', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='seller.seller')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='seller_revi_created_8bd78c_idx'), models.Index(fields=['is_approved'], name='seller_revi_is_appr_d89f61_idx')],
                'unique_together': {('seller',)},
            },
        ),
    ]
