"""
Django settings for yourbaazar project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9#dptm5wm&k7eycjw7)ufg@1gqw68qt#(68gcxpgswowt&612u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [   
     "yourbaazar.com",
    "www.yourbaazar.com",
    "yourbaazarseller.shop",
    "www.yourbaazarseller.shop",
    "127.0.0.1",
    "localhost", ]

# settings.py

CSRF_TRUSTED_ORIGINS = [
    "https://yourbaazarseller.shop",
    "https://www.yourbaazarseller.shop",
    "https://yourbaazar.com",
    "https://www.yourbaazar.com",
]

# For handling subdomain properly


# For SCRIPT_NAME support


# Application definition

INSTALLED_APPS = [
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'dal',
    # 'ratelimit',
    'dal_select2',
    'cart',
    'product',
    'order',
    'accounts',
    'payment',
    'coupon',
    'basicinfo',
    'ckeditor',
    'nested_admin',
    'wishlist',
    'product_review',
    'seller',
    'seller_products',
    'wallet',
    'seller_reviews',
    'storages',
    'seller_reports',
     'seller_api',
]

# INSTALLED_APPS += ["ratelimit"]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'yourbaazar.middleware.SellerSubdomainMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'yourbaazar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wishlist.context_processors.wishlist_count',
                'basicinfo.context_processors.basicinfo_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'yourbaazar.wsgi.application'

RATELIMIT_VIEW = "yourapp.views.ratelimit_handler"

#jazzmin
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'yourbaazardb',  # same as schema you created
#         'USER': 'admin',
#         'PASSWORD': 'tarun231',
#         'HOST': 'database-2.c3skesa0esud.ap-south-1.rds.amazonaws.com',
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yourbaazardb',  # same as schema you created
        'USER': 'admin',
        'PASSWORD': 'tarun231',
        'HOST': 'database-2.c3skesa0esud.ap-south-1.rds.amazonaws.com',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTH_USER_MODEL = 'accounts.Customer'  # Replace 'accounts' with your app name

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

CART_SESSION_ID = 'cart'

#redis caches 

# settings.py

# CACHES = {
 #   "default": {
  #      "BACKEND": "django_redis.cache.RedisCache",
   #     "LOCATION": "redis://127.0.0.1:6379/1",  # Redis DB 1
    #    "OPTIONS": {
     #       "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # Agar password set kiya hai
            # "PASSWORD": "YourStrongPasswordHere"
  #      }
 #   }
#}

# Sessions Redis me store karne ke liye
#SESSION_ENGINE = "django.contrib.sessions.backends.cache"
#SESSION_CACHE_ALIAS = "default"









# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

#STATIC_URL = '/static/'
#STATICFILES_DIRS = [BASE_DIR / 'static']
#STATIC_ROOT = BASE_DIR / 'staticfiles' 


#MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
RAZORPAY_KEY_ID = 'rzp_live_RNUvFs0ASifHRG'
RAZORPAY_KEY_SECRET = 'kgFexCGfRmJkFF7GyJmBv7Dy'





EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'yourbaazar1@gmail.com'        # replace with your email
EMAIL_HOST_PASSWORD = 'vzrl hfau llqk jdhd'       # use Gmail App Password (not regular password!)

EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER='yourbaazar1@gmail.com'
EMAIL_HOST_PASSWORD='vzrl hfau llqk jdhd'  # App Password (2FA on)
DEFAULT_FROM_EMAIL='yourbaazar1@gmail.com'
ADMIN_NOTIFY_EMAIL='administration@yourbaazar.com'  # जहाँ admin को registration mail जाए
OTP_EXPIRE_MIN=10
OTP_RESEND_COOLDOWN_SEC=60




# Shiprocket
SHIPROCKET_EMAIL = "tarunq20@gmail.com"
SHIPROCKET_PASSWORD = "4ezARgcqw$0KD0Hz"
SHIPROCKET_PICKUP = "warehouse" 
SHIPROCKET_PICKUP_PIN = "201204"           # aapke Shiprocket account ka pickup location name
# aapke Shiprocket account ka pickup location name
SHIPROCKET_CHANNEL_ID = None            # (optional) agar hai to id daal dein

# Default package dims (fallback jab product par dims na hon)
SHIPROCKET_DEFAULT_WEIGHT_KG = 0.5
SHIPROCKET_DEFAULT_LENGTH_CM = 15
SHIPROCKET_DEFAULT_BREADTH_CM = 12
SHIPROCKET_DEFAULT_HEIGHT_CM = 5












# # AWS Credentials
# AWS_ACCESS_KEY_ID = "AKIA5OUQZGJ76IBP32WS"
# AWS_SECRET_ACCESS_KEY = "GsnLc3HN7pKRqKCpNKwCI1A6hdXEg1U5IhEukZNA"
# AWS_STORAGE_BUCKET_NAME = "yourbaazar-bucket"
# AWS_S3_REGION_NAME = "ap-south-1"
# AWS_S3_FILE_OVERWRITE = False
# AWS_DEFAULT_ACL = None

# AWS_S3_CUSTOM_DOMAIN = "cdn.yourbaazar.com"

# # Custom Storages
# STORAGES = {
#     "default": {
#         "BACKEND": "yourbaazar.storages_backends.MediaStorage",
#     },
#     "staticfiles": {
#         "BACKEND": "yourbaazar.storages_backends.StaticStorage",
#     },
# }


# URL settings
# STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
# MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"

# Optional local fallback (sirf development ke liye)
# AWS Credentials
AWS_ACCESS_KEY_ID = "#"
AWS_SECRET_ACCESS_KEY = "#"
AWS_STORAGE_BUCKET_NAME = "yourbaazar-bucket"
AWS_S3_REGION_NAME = "ap-south-1"
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

AWS_S3_CUSTOM_DOMAIN = "cdn.yourbaazar.com"

# Custom Storages
STORAGES = {
    "default": {
        "BACKEND": "yourbaazar.storages_backends.MediaStorage",
    },
    "staticfiles": {
        "BACKEND": "yourbaazar.storages_backends.StaticStorage",
    },
}
STATICFILES_DIRS = [
    BASE_DIR / "static",  # agar tumhara project root me static folder hai
]


# URL settings
STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"

# Optional local fallback (sirf development ke liye)
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "mediafiles"







