# Generated by Django 5.2.3 on 2025-07-28 00:41
import uuid
from django.db import migrations, models
from django.utils import timezone
from django.conf import settings


def generate_order_number():
    """Generate order number for migration"""
    date_part = timezone.now().strftime('%Y%m%d')
    unique_part = uuid.uuid4().hex[:6].upper()
    return f"ORD-{date_part}-{unique_part}"


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(
                default=generate_order_number,  # Use the local function
                editable=False,
                max_length=20,
                unique=True
            ),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='order_order_order_n_fb1851_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_id'], name='order_order_trackin_474181_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_order_created_ffede0_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product', 'variant'), name='unique_order_item'),
        ),
    ]