# Generated by Django 5.2.3 on 2025-07-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tax_rate',
        ),
    ]
