# Generated by Django 5.2.3 on 2025-07-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_tax_amount_remove_orderitem_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiprocket_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
