# Generated by Django 5.2.3 on 2025-07-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_shiprocket_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
