# Generated by Django 5.2.3 on 2025-08-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_orderitem_discount_price_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tax_rate',
        ),
    ]
