# Generated by Django 5.2.3 on 2025-08-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_orderitem_seller_orderitem_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
