# Generated by Django 5.2.3 on 2025-09-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_shipment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_zip_code',
            new_name='shipping_pin_code',
        ),
    ]
