# Generated by Django 5.2.3 on 2025-09-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_returnrequest_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='customer_email',
            field=models.EmailField(default='defaul@gamil.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='customer_name',
            field=models.CharField(default='jhon', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='customer_phone',
            field=models.CharField(default='99', max_length=20),
            preserve_default=False,
        ),
    ]
