# Generated by Django 5.2.3 on 2025-09-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_customer_email_alter_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
