# Generated by Django 5.2.3 on 2025-09-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
